Refactor names and add support for user without sudo

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -9,19 +9,19 @@ __compose_exe="docker compose"
 __compose_upgraded=0
 
 
-dodocker() {
+__dodocker() {
   $__docker_sudo $__docker_exe "$@"
 }
 
 
-docompose() {
+__docompose() {
 # I want word splitting here
 # shellcheck disable=SC2086
   $__docker_sudo $__compose_exe "$@"
 }
 
 
-determine_distro() {
+__determine_distro() {
   # Determine OS platform
   __uname=$(uname | tr "[:upper:]" "[:lower:]")
   # If Linux, try to determine specific distribution
@@ -42,24 +42,36 @@ determine_distro() {
   __distro=$(echo "$__distro" | tr "[:upper:]" "[:lower:]")
 
   if [[ "$__distro" = "ubuntu" ]]; then
-    if ! dpkg-query -W -f='${Status}' lsb-release 2>/dev/null | grep -q "ok installed"; then
-      ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get -y install lsb-release
+    if [ "$__cannot_sudo" -eq 0 ]; then
+      if ! dpkg-query -W -f='${Status}' lsb-release 2>/dev/null | grep -q "ok installed"; then
+        ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get -y install lsb-release
+      fi
     fi
-    __os_major_version=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'// | cut -d. -f1)
+    if [ -n "$(command -v lsb_release 2>/dev/null)" ]; then
+      __os_major_version=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'// | cut -d. -f1)
+    else
+      __os_major_version=24 # Without sudo and lsb_release let's just skip the check
+    fi
   elif [[ "$__distro" =~ "debian" ]]; then
-    if ! dpkg-query -W -f='${Status}' lsb-release 2>/dev/null | grep -q "ok installed"; then
-      ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get -y install lsb-release
+    if [ "$__cannot_sudo" -eq 0 ]; then
+      if ! dpkg-query -W -f='${Status}' lsb-release 2>/dev/null | grep -q "ok installed"; then
+        ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get -y install lsb-release
+      fi
     fi
-    __os_major_version=$(lsb_release -r | cut -f2)
+    if [ -n "$(command -v lsb_release 2>/dev/null)" ]; then
+      __os_major_version=$(lsb_release -r | cut -f2)
+    else
+      __os_major_version=12 # Without sudo and lsb_release let's just skip the check
+    fi
   fi
 }
 
 
-handle_docker_sudo() {
+__handle_docker_sudo() {
   if [[ "$__distro" =~ "debian" || "$__distro" = "ubuntu" ]]; then
     systemctl status docker >/dev/null
-    result=$?
-    if [ ! "${result}" -eq 0 ]; then
+    __result=$?
+    if [ ! "${__result}" -eq 0 ]; then
       echo "The Docker daemon is not running. Please check Docker installation."
       echo "\"sudo systemctl status docker\" and \"sudo journalctl -fu docker\" will be helpful."
       echo "Aborting."
@@ -78,24 +90,34 @@ handle_docker_sudo() {
 
   __docker_sudo=""
   if ! docker images >/dev/null 2>&1; then
+    if [ "$__cannot_sudo" -eq 1 ]; then
+      echo "Cannot call Docker and cannot use sudo. Please make your user part of the docker group"
+      exit 1
+    fi
     echo "Will use sudo to access Docker"
     __docker_sudo="sudo"
   fi
 }
 
 
-handle_root() {
+__handle_root() {
+  __cannot_sudo=0
   if [ "${EUID}" -eq 0 ]; then
     __as_owner="sudo -u ${OWNER}"
     __auto_sudo=""
   else
     __as_owner=""
-    __auto_sudo="sudo"
+    if groups | grep -q '\bsudo\b' || groups | grep -q '\badmin\b'; then
+      __auto_sudo="sudo"
+    else
+      __auto_sudo=""
+      __cannot_sudo=1
+    fi
   fi
 }
 
 
-check_compose_version() {
+__check_compose_version() {
 # Check for Compose V2 (docker compose) vs Compose V1 (docker-compose)
   if docker compose version >/dev/null 2>&1; then
     __old_compose=0
@@ -109,10 +131,10 @@ check_compose_version() {
       echo
       echo "It is recommended that you replace Compose V1 with Compose V2."
       while true; do
-        read -rp "Do you want to update Docker Compose to V2? (yes/no) " yn
-        case $yn in
+        read -rp "Do you want to update Docker Compose to V2? (yes/no) " __yn
+        case $__yn in
           [Nn]* ) echo "Please be sure to update Docker Compose yourself!"; break;;
-           * ) upgrade_compose; break;;
+           * ) __upgrade_compose; break;;
         esac
       done
     fi
@@ -120,7 +142,7 @@ check_compose_version() {
 }
 
 
-upgrade_compose() {
+__upgrade_compose() {
   if ! type -P docker-compose >/dev/null 2>&1; then
     echo "Docker Compose has already been updated to V2"
     return
@@ -174,7 +196,7 @@ upgrade_compose() {
 }
 
 
-check_for_snap() {
+__check_for_snap() {
   if [[ "$__distro" = "ubuntu" && -n "$(which snap)" ]] && snap list 2>/dev/null | grep -qw 'docker'; then
     echo
     echo "WARNING! Snap Docker package detected. This WILL result in issues."
@@ -195,9 +217,14 @@ check_for_snap() {
 
 
 install() {
+  if [ "$__cannot_sudo" -eq 1 ]; then
+    echo "The install command requires the user to be part of the sudo group, or on macOS the admin group"
+    exit 1
+  fi
+
   while true; do
-    read -rp "This will attempt to install Docker and make your user part of the docker group. Do you wish to continue? (no/yes) " yn
-    case $yn in
+    read -rp "This will attempt to install Docker and make your user part of the docker group. Do you wish to continue? (no/yes) " __yn
+    case $__yn in
       [Yy]* ) break;;
       * ) echo "Aborting, no changes made"; exit 130;;
     esac
@@ -270,17 +297,17 @@ install() {
 
 __get_docker_free_space() { # set __free_space to what's available to Docker
   if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
-    __free_space=$(dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy | awk '/[0-9]%/{print $(NF-2)}')
+    __free_space=$(__dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy | awk '/[0-9]%/{print $(NF-2)}')
   else
-    __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
+    __docker_dir=$(__dodocker system info --format '{{.DockerRootDir}}')
     __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
   fi
 
-  re='^[0-9]+$'
-  if ! [[ "${__free_space}" =~ $re ]] ; then
+  __regex='^[0-9]+$'
+  if ! [[ "${__free_space}" =~ $__regex ]] ; then
     echo "Unable to determine free disk space. This is likely a bug."
     if [[ "$OSTYPE" == "darwin"* ]]; then
-      echo "df reports $(dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy) and __free_space is ${__free_space}"
+      echo "df reports $(__dodocker run --rm -v macos-space-check:/dummy busybox df -P /dummy) and __free_space is ${__free_space}"
     else
       echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
     fi
@@ -292,7 +319,7 @@ __get_docker_free_space() { # set __free_space to what's available to Docker
 __display_docker_dir() {
   if [[ "$OSTYPE" == "darwin"* ]]; then # macOS doesn't expose docker root dir to the OS
     echo "Here's total and used space on Docker's virtual volume"
-    dodocker run --rm -v macos-space-check:/dummy busybox df -h /dummy
+    __dodocker run --rm -v macos-space-check:/dummy busybox df -h /dummy
   else
     echo "Here's total and used space on ${__docker_dir}"
     df -h "${__docker_dir}"
@@ -302,12 +329,12 @@ __display_docker_dir() {
 
 __display_docker_volumes() {
   echo
-  if [ -z "$(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
+  if [ -z "$(__dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_[^_]+")" ]; then
     echo "There are no Docker volumes for this copy of ${__project_name}"
     echo
   else
     echo "Here are the Docker volumes used by this copy of ${__project_name} and their space usage:"
-    dodocker system df -v | grep -A 50 "VOLUME NAME" | grep "^$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
+    __dodocker system df -v | grep -A 50 "VOLUME NAME" | grep "^$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"
     echo
   fi
   echo "If there is some mystery space being taken up, try \"sudo ncdu /\"."
@@ -330,7 +357,7 @@ space() {
 
 
 # Warn user if space is low, so they can prune
-check_disk_space() {
+__check_disk_space() {
   __get_docker_free_space
 
   if [[ "${__free_space}" -lt 52428800 ]]; then
@@ -346,27 +373,29 @@ check_disk_space() {
 }
 
 
-nag_os_version() {
+__nag_os_version() {
   if [[ "$__distro" = "ubuntu" ]]; then
     if [ "${__os_major_version}" -lt 22 ]; then
       echo
       echo "Ubuntu ${__os_major_version} is older than the recommended 24.04 or 22.04 version."
       echo
+      echo "Updating is neither urgent nor required, merely recommended."
     fi
   elif [[ "$__distro" =~ "debian" ]]; then
     if [ "${__os_major_version}" -lt 11 ]; then
       echo
       echo "Debian ${__os_major_version} is older than the recommended 12 or 11 version."
       echo
+      echo "Updating is neither urgent nor required, merely recommended."
     fi
   fi
 }
 
 
-pull_and_build() {
-  dodocker system prune --force
-  docompose --profile tools pull
-  docompose --profile tools build --pull
+__pull_and_build() {
+  __dodocker system prune --force
+  __docompose --profile tools pull
+  __docompose --profile tools build --pull
 }
 
 
@@ -382,8 +411,8 @@ update() {
 
   __free_space=$(df -P "$(pwd)" | awk '/[0-9]%/{print $(NF-2)}')
 
-  re='^[0-9]+$'
-  if ! [[ "${__free_space}" =~ $re ]] ; then
+  __regex='^[0-9]+$'
+  if ! [[ "${__free_space}" =~ $__regex ]] ; then
     echo "Unable to determine free disk space. This is likely a bug."
     echo "df reports $(df -P "$(pwd)") and __free_space is ${__free_space}"
     exit 70
@@ -403,9 +432,9 @@ update() {
   if [ -z "${ETHDSECUNDO-}" ]; then
     set +e
     ${__as_owner} git config pull.rebase false
-    var="SCRIPT_TAG"
-    value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}" || true)
-    if [ -z "${value}" ] || [ "${value}" = "latest" ]; then
+    __var="SCRIPT_TAG"
+    __value=$(sed -n -e "s/^${__var}=\(.*\)/\1/p" "${__env_file}" || true)
+    if [ -z "${__value}" ] || [ "${__value}" = "latest" ]; then
       export ETHDPINNED=""
       __branch=$(git rev-parse --abbrev-ref HEAD)
       if [[ "${__branch}" =~ ^tag-v[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
@@ -413,9 +442,9 @@ update() {
       fi
       ${__as_owner} git pull
     else
-      export ETHDPINNED="${value}"
+      export ETHDPINNED="${__value}"
       ${__as_owner} git fetch --tags
-      ${__as_owner} git checkout -B "tag-${value}" "tags/${value}"
+      ${__as_owner} git checkout -B "tag-${__value}" "tags/${__value}"
     fi
     export GITEXITCODE=$?
     set -e
@@ -425,22 +454,22 @@ update() {
     exec "${BASH_SOURCE[0]}" update "$@"
   fi
 
-  envmigrate
-  pull_and_build
+  __env_migrate
+  __pull_and_build
 
-  if [ "${__migrated}" -eq 1 ] && ! cmp -s "${ENV_FILE}" "${ENV_FILE}".source; then
-    cp "${ENV_FILE}".source "${ENV_FILE}".bak
-    rm "${ENV_FILE}".source
-    echo "Your ${ENV_FILE} configuration settings have been migrated to a fresh copy. You can \
-find the original contents in ${ENV_FILE}.bak."
+  if [ "${__migrated}" -eq 1 ] && ! cmp -s "${__env_file}" "${__env_file}".source; then
+    cp "${__env_file}".source "${__env_file}".bak
+    rm "${__env_file}".source
+    echo "Your ${__env_file} configuration settings have been migrated to a fresh copy. You can \
+find the original contents in ${__env_file}.bak."
     echo
-    echo "List of changes made to ${ENV_FILE} during migration - current on left, original on right:"
+    echo "List of changes made to ${__env_file} during migration - current on left, original on right:"
     echo
-    diff -y --suppress-common-lines "${ENV_FILE}" "${ENV_FILE}".bak || true
+    diff -y --suppress-common-lines "${__env_file}" "${__env_file}".bak || true
   else
-    echo "No changes made to ${ENV_FILE} during update"
-    if [ -f "${ENV_FILE}".source ]; then
-      ${__as_owner} rm "${ENV_FILE}".source || true
+    echo "No changes made to ${__env_file} during update"
+    if [ -f "${__env_file}".source ]; then
+      ${__as_owner} rm "${__env_file}".source || true
     fi
   fi
   echo
@@ -456,7 +485,7 @@ find the original contents in ${ENV_FILE}.bak."
     echo "The current partial update risks startup failure."
   fi
 
-  nag_os_version
+  __nag_os_version
 
   unset ETHDSECUNDO
   unset GITEXITCODE
@@ -478,52 +507,52 @@ find the original contents in ${ENV_FILE}.bak."
 }
 
 
-envmigrate() {
-  if [ ! -f "${ENV_FILE}" ]; then
+__env_migrate() {
+  if [ ! -f "${__env_file}" ]; then
     return 0
   fi
 
 # Adjust these vars to your project
-  ALL_VARS=( COMPOSE_FILE NETWORK SNAPSHOT LOG_LEVEL DOMAIN RPC_HOST RPC_LB WS_HOST WS_LB RPC_PORT WS_PORT P2P_PORT \
+  __all_vars=( COMPOSE_FILE NETWORK SNAPSHOT LOG_LEVEL DOMAIN RPC_HOST RPC_LB WS_HOST WS_LB RPC_PORT WS_PORT P2P_PORT \
              SCRIPT_TAG X_SRC_BUILD_TARGET X_SRC_REPO X_DOCKER_TAG X_DOCKER_REPO X_DOCKERFILE )
-  OLD_VARS=( )
-  NEW_VARS=( )
+  __old_vars=( )
+  __new_vars=( )
 
-  var=ENV_VERSION
-  __target_ver=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "default.env" || true)
-  __source_ver=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}" || true)
+  __var=ENV_VERSION
+  __target_ver=$(sed -n -e "s/^${__var}=\(.*\)/\1/p" "default.env" || true)
+  __source_ver=$(sed -n -e "s/^${__var}=\(.*\)/\1/p" "${__env_file}" || true)
 
   if [[ "${__target_ver}" -le "${__source_ver}" ]]; then # No changes in template, do nothing
     return 0
   fi
 
-  echo "Migrating ${ENV_FILE} to version ${__target_ver}"
-  ${__as_owner} cp "${ENV_FILE}" "${ENV_FILE}".source
+  echo "Migrating ${__env_file} to version ${__target_ver}"
+  ${__as_owner} cp "${__env_file}" "${__env_file}".source
   __during_migrate=1
   __migrated=1
-  ${__as_owner} cp default.env "${ENV_FILE}"
+  ${__as_owner} cp default.env "${__env_file}"
   # Migrate over user settings
-  for var in "${ALL_VARS[@]}"; do
-    value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}.source" || true)
+  for __var in "${__all_vars[@]}"; do
+    __value=$(sed -n -e "s/^${__var}=\(.*\)/\1/p" "${__env_file}.source" || true)
 # Adjust for vars that are possibly empty
-    if [ -n "${value}" ] || [ "${var}" = "SNAPSHOT" ]; then
-      sed -i'.original' -e "s~^\(${var}\s*=\s*\).*$~\1${value}~" "${ENV_FILE}"
+    if [ -n "${__value}" ] || [ "${__var}" = "SNAPSHOT" ]; then
+      sed -i'.original' -e "s~^\(${__var}\s*=\s*\).*$~\1${__value}~" "${__env_file}"
     fi
   done
   # Move value from old variable name(s) to new one(s)
-  for index in "${!OLD_VARS[@]}"; do
-    var=${OLD_VARS[index]}
-    value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}.source" || true)
-    if [ -n "${value}" ]; then
-      sed -i'.original' -e "s~^\(${NEW_VARS[index]}\s*=\s*\).*$~\1${value}~" "${ENV_FILE}"
+  for __index in "${!__old_vars[@]}"; do
+    __var=${__old_vars[__index]}
+    __value=$(sed -n -e "s/^${__var}=\(.*\)/\1/p" "${__env_file}.source" || true)
+    if [ -n "${__value}" ]; then
+      sed -i'.original' -e "s~^\(${__new_vars[__index]}\s*=\s*\).*$~\1${__value}~" "${__env_file}"
     fi
   done
-  rm "${ENV_FILE}".original
+  rm "${__env_file}".original
   __during_migrate=0
 }
 
 
-prep_conffiles() {
+__prep_conffiles() {
 # Create ext-network.yml if it doesn't exist
   if [ ! -f "ext-network.yml" ]; then
     ${__as_owner} cp ext-network.yml.sample ext-network.yml
@@ -537,7 +566,7 @@ upgrade() {
 
 
 start() {
-  docompose up -d --remove-orphans "$@"
+  __docompose up -d --remove-orphans "$@"
 }
 
 
@@ -552,7 +581,7 @@ run() {
 
 
 stop() {
-  docompose down --remove-orphans "$@"
+  __docompose down --remove-orphans "$@"
 }
 
 
@@ -570,25 +599,25 @@ restart() {
 
 
 logs() {
-  docompose logs "$@"
+  __docompose logs "$@"
 }
 
 
 cmd() {
-  docompose "$@"
+  __docompose "$@"
 }
 
 
 terminate() {
-  if [ -z "$(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_.+")" ]; then
+  if [ -z "$(__dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_.+")" ]; then
     echo "There are no data stores - Docker volumes - left to remove for this ${__app_name}."
     stop
     exit 0
   fi
 
   while true; do
-    read -rp "WARNING - this action will destroy all data stores for this ${__app_name}. Do you wish to continue? (No/Yes) " yn
-    case $yn in
+    read -rp "WARNING - this action will destroy all data stores for this ${__app_name}. Do you wish to continue? (No/Yes) " __yn
+    case $__yn in
       [Yy]es ) break;;
       * ) echo "Aborting, no changes made"; exit 130;;
     esac
@@ -597,35 +626,35 @@ terminate() {
   down
 # In this case I want the word splitting, so rm can remove all volumes
 # shellcheck disable=SC2046
-  dodocker volume rm $(dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_.+")
+  __dodocker volume rm $(__dodocker volume ls -q -f "name=^$(basename "$(realpath .)")_.+")
   echo
   echo "All containers stopped and all volumes deleted"
   echo
 }
 
 
-handle_error() {
+__handle_error() {
   if [[ ! $- =~ e ]]; then
 # set +e, do nothing
     return 0
   fi
 
-  local exit_code=$1
-  local line_no=$2
-  if [ "$exit_code" -eq 130 ]; then
+  local __exit_code=$1
+  local __line_no=$2
+  if [ "$__exit_code" -eq 130 ]; then
     echo "$__me terminated by user"
   else
-    echo "$__me terminated with exit code $exit_code on line $line_no"
+    echo "$__me terminated with exit code $__exit_code on line $__line_no"
     if [ -n "${__command}" ]; then
       echo "This happened during $__me ${__command} ${__params}"
     fi
   fi
   if [ "$__during_update" -eq 1 ] && [ "$__during_migrate" -eq 1 ]; then
-    cp "${ENV_FILE}" "${ENV_FILE}".partial
-    cp "${ENV_FILE}".source "${ENV_FILE}"
+    cp "${__env_file}" "${__env_file}".partial
+    cp "${__env_file}".source "${__env_file}"
     echo
-    echo "Restored your ${ENV_FILE} file, to undo partial migration. Please verify it looks correct."
-    echo "The partially migrated file is in ${ENV_FILE}.partial for troubleshooting."
+    echo "Restored your ${__env_file} file, to undo partial migration. Please verify it looks correct."
+    echo "The partially migrated file is in ${__env_file}.partial for troubleshooting."
   fi
 }
 
@@ -634,13 +663,13 @@ version() {
 # script version
   grep "^This is" README.md
   echo
-  var="COMPOSE_FILE"
-  value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" "${ENV_FILE}" || true)
+  __var="COMPOSE_FILE"
+  __value=$(sed -n -e "s/^${__var}=\(.*\)/\1/p" "${__env_file}" || true)
 # Client versions
 # Adjust for your clients and how to check their version
-  case "${value}" in
+  case "${__value}" in
     *x.yml* )
-      docompose exec x-geth x-geth version
+      __docompose exec x-geth x-geth version
       ;;&
   esac
 }
@@ -685,14 +714,14 @@ help() {
 
 
 # Main body from here
-ENV_FILE=.env
+__env_file=.env
 __during_update=0
 __during_migrate=0
 __migrated=0
 __command=""
 __me="./$(basename "${BASH_SOURCE[0]}")"
 
-trap 'handle_error $? $LINENO' ERR
+trap '__handle_error $? $LINENO' ERR
 
 if [[ "$#" -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
   help
@@ -713,19 +742,19 @@ __command="$1"
 shift
 __params=$*
 
-handle_root
-determine_distro
-prep_conffiles
+__handle_root
+__determine_distro
+__prep_conffiles
 
-check_for_snap
+__check_for_snap
 
 if [ "$__command" = "install" ]; then
   $__command "$@"
   exit "$?"
 fi
 
-handle_docker_sudo
-check_compose_version
+__handle_docker_sudo
+__check_compose_version
 
 if [ "${__old_compose}" -eq 1 ]; then
   echo
@@ -748,12 +777,12 @@ if [ "${__old_docker}" -eq 1 ]; then
   exit 0
 fi
 
-if ! dodocker images >/dev/null 2>&1; then
+if ! __dodocker images >/dev/null 2>&1; then
   echo "Please ensure you can call $__docker_exe before running ${__me}."
   exit 1
 fi
 
-if ! docompose --help >/dev/null 2>&1; then
+if ! __docompose --help >/dev/null 2>&1; then
   echo "Please ensure you can call $__compose_exe before running ${__me}."
   exit 1
 fi
@@ -767,7 +796,7 @@ case "$__command" in
     ;;
 esac
 
-check_disk_space
+__check_disk_space
 
 if [ "${__compose_upgraded}" -eq 1 ]; then
   echo
